default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: teleport_development

test:
  <<: *default
  database: teleport_test

staging:
  <<: *default
  database: teleport_staging

production:
  <<: *default
  database: teleport_production
